global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "vetautet-prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9090"]
    metrics_path: /metrics

  - job_name: "vetautet-application"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:1122" ]
    metrics_path: /actuator/prometheus

  - job_name: "vetautet-node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9100" ]

  - job_name: "vetautet-mysql-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9104" ]
    metrics_path: /metrics

  - job_name: "vetautet-redis-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9121" ]
    metrics_path: /metrics

  - job_name: 'vetautet-postgres-exporter'
    honor_labels: true
    scrape_interval: 5s
#    scrape_timeout: 60s
    static_configs:
      - targets: [ 'host.docker.internal:9187' ]
    metrics_path: '/metrics'